default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: sayumi729864
  host: localhost

development:
  <<: *default
  database: pokemon_dungeon_dx_club_development

test:
  <<: *default
  database: pokemon_dungeon_dx_club_test

production:
  <<: *default
  database: pokemon_dungeon_dx_club_production
  username: pokemon_dungeon_dx_club
  password: <%= ENV['POKEMON_DUNGEON_DX_CLUB_DATABASE_PASSWORD'] %>
