Type.create(name: 'ノーマル', image: 'normal.png', color: 'wheat')
Type.create(name: 'ほのお', image: 'fire.png', color: 'orangered')
Type.create(name: 'みず', image: 'water.png', color: 'royalblue')
Type.create(name: 'くさ', image: 'grass.png', color: 'lime')
Type.create(name: 'でんき', image: 'electric.png', color: 'yellow')
Type.create(name: 'こおり', image: 'ice.png', color: 'cyan')
Type.create(name: 'かくとう', image: 'fighting.png', color: 'orange')
Type.create(name: 'どく', image: 'poison.png', color: 'purple')
Type.create(name: 'じめん', image: 'ground.png', color: 'goldenrod')
Type.create(name: 'ひこう', image: 'flying.png', color: 'lightskyblue')
Type.create(name: 'エスパー', image: 'psychic.png', color: 'hotpink')
Type.create(name: 'むし', image: 'bug.png', color: 'yellowgreen')
Type.create(name: 'いわ', image: 'rock.png', color: 'saddlebrown')
Type.create(name: 'ゴースト', image: 'ghost.png', color: 'blueviolet')
Type.create(name: 'ドラゴン', image: 'dragon.png', color: 'slateblue')
Type.create(name: 'あく', image: 'dark.png', color: 'black')
Type.create(name: 'はがね', image: 'steel.png', color: 'lightsteelblue')
Type.create(name: 'フェアリー', image: 'fairy.png', color: 'lightpink')

Quality.create(name: 'ごりおし')
Quality.create(name: 'すぐまんぷく')
Quality.create(name: 'くうにこまらず')
Quality.create(name: 'オニせいちょう')
Quality.create(name: 'れんぞくひっちゅう')
Quality.create(name: 'わきあいあい')
Quality.create(name: 'したしみやすい')
Quality.create(name: 'PPのひけつ')
Quality.create(name: 'いっしむくいる')
Quality.create(name: 'うりつけテクニック')
Quality.create(name: 'おおたちまわり')
Quality.create(name: 'かいひのリズム')
Quality.create(name: 'かいふくじまん')
Quality.create(name: 'けいかいほこう')
Quality.create(name: 'げんきにつられる')
Quality.create(name: 'しぼりだす')
Quality.create(name: 'ぜっしょくじまん')
Quality.create(name: 'せまいところがすき')
Quality.create(name: 'ちゆりょくじまん')
Quality.create(name: 'つうろひっちゅう')
Quality.create(name: 'なげものアップ')
Quality.create(name: 'ねびきこうしょう')
Quality.create(name: 'ばくはつけいかい')
Quality.create(name: 'はなれてもがんばる')
Quality.create(name: 'はんどうアップ')
Quality.create(name: 'はんぶんのこす')
Quality.create(name: 'まえにとびだす')
Quality.create(name: 'まけずぎらい')
Quality.create(name: 'まもりのリズム')
Quality.create(name: 'みちをつくる')
Quality.create(name: 'みっしゅうじんけい')
Quality.create(name: 'やまいはきから')
Quality.create(name: 'れんけつアップ')
Quality.create(name: 'わざせいちょう')

User.create(name: 'Sylpha', email: 'sylpha.games@gmail.com', password: 'sayumi729864')
